name: hongshanshengkong
on:
  workflow_dispatch:

  schedule:
    - cron: '54 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongshanshengkong
        env:
          drzkx3162: ${{ secrets.drzkx3162 }}
        run: |
          printf '%s' "$drzkx3162" | jq -r .mep1037 | /bin/bash
          printf '%s' "$y543" | jq -r .pctcb046 | /bin/bash
          printf '%s' "$nmhs5" | jq -r .oyzm631 | /bin/bash
          echo $ro41 | jq -r .pdt62382 | /bin/bash
          echo $ezyvt10428 | jq -r .kkolr58088 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4w561CyR
          path: "*.zip"
          retention-days: 1
